### PR TITLE
[Doc Only] Add test command to README

### PR DESCRIPTION
**Pull request by onishik88**
I was in trouble because I did not understand how to test when adding features.
So, I added test command to README :)

### CODE REVIEW

**Comment by mocobeta** [comment]
Thanks for the request. 
There is a wiki page for contributors, this includes test command: https://github.com/mocobeta/janome/wiki
Maybe should we add this link in the README?

**Comment by onishik88** [comment]
I overlooked this wiki link... sorry...
As you say, I think it is appropriate to add this wiki link, instead of test command.

**Comment by mocobeta** [comment]
Thanks, I would like to modify this a little:

> Contributing

to "For contributors"

> Check out wiki page:

to "Please see this wiki page:"

Can you please update the PR? :)

**Comment by mocobeta** [comment]
I just merged. Thank you!

**Pull request merged**
